services:
  api:
    build: .
    image: steam-recommender:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - UV_NO_TELEMETRY=1
  frontend:
    build: .
    image: steam-recommender:latest
    depends_on:
      - api
    command: ["uv", "run", "streamlit", "run", "src-front/streamlit_app.py", "--server.port", "9000", "--server.headless", "true"]
    environment:
      - API_URL=http://api:8000
    ports:
      - "9000:9000"

